export const agentInfo = [
  {
    No: 1,
    Agent: "Brimstone",
    Role: "Controller",
    Voice: "Steve Blum",
    mg: "",
  },
  {
    No: 2,
    Agent: "Viper",
    Role: "Controller",
    Voice: "Ashly Burch",
    img: "",
  },
  {
    No: 3,
    Agent: "Omen",
    Role: "Controller",
    Voice: "Jason Marnocha",
    img: "",
  },
  {
    No: 4,
    Agent: "Killjoy",
    Role: "Sentinel",
    Voice: "Eva Feiler",
    img: "",
  },
  {
    No: 5,
    Agent: "Cypher",
    Role: "Sentinel",
    Voice: "Nabil Elouahabi",
    img: "",
  },
  {
    No: 6,
    Agent: "Sova",
    Role: "Initiator",
    Voice: "Aaron Vodovoz",
    img: "",
  },
  {
    No: 7,
    Agent: "Sage",
    Role: "Sentinel",
    Voice: "Naomi Yang",
    img: "",
  },
  {
    No: 9,
    Agent: "Phoenix",
    Role: "Duelist",
    Voice: "Afolabi Alli",
    img: "",
  },
  {
    No: 10,
    Agent: "Jett",
    Role: "Duelist",
    Voice: "Shannon Williams",
    img: "",
  },
  {
    No: 11,
    Agent: "Reyna",
    Role: "Duelist",
    Voice: "Karina Altamirano",
    img: "",
  },
  {
    No: 12,
    Agent: "Raze",
    Role: "Duelist",
    Voice: "Carolina Ravassa",
    img: "",
  },
  {
    No: 13,
    Agent: "Breach",
    Role: "Initiator",
    Voice: "David Menkin",
    img: "",
  },
  {
    No: 14,
    Agent: "Skye",
    Role: "Initiator",
    Voice: "Miranda O'Hare",
    img: "",
  },
  {
    No: 15,
    Agent: "Yoru",
    Role: "Duelist",
    Voice: "Daisuke Takahashi",
    img: "",
  },
  {
    No: 16,
    Agent: "Astra",
    Role: "Controller",
    Voice: "Effie Nkrumah",
    img: "",
  },
  {
    No: 17,
    Agent: "KAY/O",
    Role: "Initiator",
    Voice: "Gabe Kunda",
    img: "",
  },
  {
    No: 18,
    Agent: "Chamber",
    Role: "Sentinel",
    Voice: "Hugo Pierre Martin",
    img: "",
  },
  {
    No: 19,
    Agent: "Neon",
    Role: "Duelist",
    Voice: "Vanille Velasquez",
    img: "",
  },
  {
    No: 20,
    Agent: "Fade",
    Role: "Initiator",
    Voice: "Selin Çuhadaroğlu",
    img: "",
  },
  {
    No: 21,
    Agent: "Harbor",
    Role: "Controller",
    Voice: "Sunil Malhotra",
    img: "",
  },
  {
    No: 22,
    Agent: "Gekko",
    Role: "Initiator",
    Voice: "Alejandro Antonio Ruiz",
    img: "",
  },
  {
    No: 23,
    Agent: "Deadlock",
    Role: "Sentinel",
    Voice: "Nora Gjestvang",
    img: "",
  },
  {
    No: 24,
    Agent: "Iso",
    Role: "Duelist",
    Voice: "Unknown",
    img: "",
  },
  {
    No: 25,
    Agent: "Clove",
    Role: "Controller",
    Voice: "Isla Campbell",
    img: "",
  },
  {
    No: 26,
    Agent: "Vyse",
    Role: "Sentinel",
    Voice: "Marta Svetek",
    img: "",
  },
];
